import{a as h,S as y,i as n}from"./assets/vendor-CFFvTae-.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&u(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const g="56499472-080893bfed44fcf3a0d134fcd",v="https://pixabay.com/api/";async function L(e,a=1){return(await h.get(v,{params:{key:g,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),b=new y(".gallery a",{captionsData:"alt",captionDelay:250}),w=()=>d.innerHTML="",S=()=>f.classList.remove("is-hidden"),q=()=>f.classList.add("is-hidden"),B=()=>m.classList.remove("is-hidden"),R=()=>m.classList.add("is-hidden");function $(e){const a=e.map(s=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s.largeImageURL}">
        <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
      </a>
      <div class="info-block">
        <div class="info-item"><b class="info-title">Likes</b><span class="info-value">${s.likes}</span></div>
        <div class="info-item"><b class="info-title">Views</b><span class="info-value">${s.views}</span></div>
        <div class="info-item"><b class="info-title">Comments</b><span class="info-value">${s.comments}</span></div>
        <div class="info-item"><b class="info-title">Downloads</b><span class="info-value">${s.downloads}</span></div>
      </div>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",a),b.refresh()}function M(){const e=d.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}const P=document.querySelector(".form"),I=document.querySelector(".load-more");let l="",r=1,c=0;const p=async()=>{R(),S();try{const e=await L(l,r);if(!e.hits.length){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}$(e.hits),c+=e.hits.length,r>1&&M(),c>=e.totalHits?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):B()}catch{n.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{q()}};P.addEventListener("submit",async e=>{e.preventDefault(),l=e.currentTarget.elements["search-text"].value.trim(),l&&(r=1,c=0,w(),await p())});I.addEventListener("click",async()=>{r+=1,await p()});
//# sourceMappingURL=index.js.map
